### PR TITLE
Added more shoes

### PR DESCRIPTION
**Pull request by Dibyendu303**
#15 Added more shoes in the shoes component. Also created a shoeItem component to avoid repition of code while creating more shoes.
Screenshot (1897)

### CODE REVIEW

**Comment by rohan9024** [comment]
@Dibyendu303 ohhh that's great! Can you do this with other routes as well like men shirts, women clothes and kids as well ........I will provide you extra points if you do so........

**Comment by Dibyendu303** [comment]
Yeah sure

**Comment by Dibyendu303** [comment]
Issue #15 Created men, kids and women page and added products in each categories.
Screenshot (1898)
Screenshot (1899)
Screenshot (1900)

**Comment by Dibyendu303** [comment]
@rohan9024 I haven't received points for this PR. Please check.

**Comment by rohan9024** [comment]
@Dibyendu303 now check

**Comment by Dibyendu303** [comment]
@rohan9024 Got it. Thanks.

**Pull request merged**
