### PR TITLE
Created a responsive navbar with hamburger menu

### PR DESCRIPTION
**Pull request by Dibyendu303**
Issue #20 .Screenshot attched below:
Screenshot (1916)
Screenshot (1917)

### CODE REVIEW

**Comment by Dibyendu303** [comment]
Screenshot (1918)
@rohan9024 is this fine ?

**Comment by rohan9024** [comment]
@Dibyendu303 bring the previous navbar 

image

Give spacing as it was before 


The responsiveness you have implemented is fine✔

**Comment by Dibyendu303** [comment]
@rohan9024 previous navbar will be shown in large screens. In mobile, the hamburger menu will be shown. Attached a video preview.

https://user-images.githubusercontent.com/66685553/206841887-413f4762-f771-41d8-adca-85c7a43f242b.mp4

**Comment by rohan9024** [comment]
@Dibyendu303 move search bar towards left coz its getting too close to other buttons 

Secondly, give space y to the whole navbar ....

**Comment by Dibyendu303** [comment]
Done @rohan9024 . 
Screenshot (1919)

**Comment by rohan9024** [comment]
@Dibyendu303 you need to use tailwind css for responsiveness

**Comment by rohan9024** [comment]
And also it is not responsive -->

image

**Comment by Dibyendu303** [comment]
@rohan9024. This is happening because the homepage is not responsive. If you remove other parts of the home page and keep only the navbar, it will be responsive. 
Please create one issue of making the home page responsive and assign it to me, I will fix it.

**Comment by rohan9024** [comment]
@Dibyendu303 check issues

**Comment by Dibyendu303** [comment]
Three issues solved:
1. #20 Responsive navbar with hamburger menu
2. #26 Made homepage responsive with tailwind css
3. #22 Made footer responsive with tailwind css

@rohan9024 Please check.

**Comment by rohan9024** [comment]
@Dibyendu303 great work!

**Comment by Dibyendu303** [comment]
@rohan9024 Thanks. Please award points for issue #26 and issue #22. I submitted all three solutions in a single PR.

**Pull request merged**
