### PR TITLE
validate login and signup form #138

### LINKED ISSUE #138: Validating Error and Displaying Error message to user in  registration form .
The problem is that after clicking on the register button,  registration form does not display any error messages, making it difficult for users to identify and correct input errors.

[Screencast from 2023-12-10 17-27-53.webm](https://github.com/rohan9024/ecommerce/assets/106171546/618ba100-e33f-4828-aa2e-d18893ee084f)

### PR DESCRIPTION
**Pull request by Yash-Ainapure**
Closes #138 
changes made :
* fixed validation to login form
* success toast message displayed for successful login,or register user
* error toast message displayed if login failed or register failed

Screenshot (137)

this is also applied it to register page.

### CODE REVIEW

**Comment by rohan9024** [comment]
@Yash-Ainapure Can you please resolve the conflicts?

**Comment by Yash-Ainapure** [comment]
Heyy @rohan9024  , The package-lock.json file is of 26000 lines and has 1200 conflicts .
Resolving this conflicts is not possible at now.
I just want to ask 1 question : Is this resolve conflicts occured with every ones pull requests or just mine??

Screenshot (140)

**Comment by rohan9024** [comment]
@Yash-Ainapure No, you didn't need to commit package lock😂 Wait a sec I'll do some changes in the code and then you try pushing again

**Comment by rohan9024** [comment]
@Yash-Ainapure I have done the changes👍 Try pushing once again and I have got one issue for you

**Comment by Yash-Ainapure** [comment]
> @Yash-Ainapure I have done the changes👍 Try pushing once again and I have got one issue for you

How do i push once again
Do i need to make new pr for that?

**Pull request merged**
