### PR TITLE
Make new routes for navlinks

### PR DESCRIPTION
**Pull request by DarK-VEnOM-16**

### CODE REVIEW

**Comment by DarK-VEnOM-16** [comment]
Created a folder Router and added AppRouter.js

**Comment by rohan9024** [comment]
@DarK-VEnOM-16 
image

restore the changes and add route exact path for other navlinks

**Comment by DarK-VEnOM-16** [comment]
@rohan9024 Completed the changes added Shoe , Producat Description Route  and merged conflicts

**Comment by DarK-VEnOM-16** [comment]
@rohan9024 Can you please take a look at it

**Comment by rohan9024** [comment]
@DarK-VEnOM-16 you need to make more routes ...... I think you need take up a simple issue rather jumping onto a complex once

**Pull request closed without merging**
