### PR TITLE
Make the footer links clickable  #131 Solved with Bonus

### PR DESCRIPTION
**Pull request by GauravGupta993**
#131 Solved. Created each page for 50 Points Bonus. Please tell me in case any changes are required. I will work on them.

### CODE REVIEW

**Comment by rohan9024** [comment]
@GauravGupta993 The code follows only tailwind css rather than using plain css. It just uses more memory compared to tailwind. Delete all css files and use tailwind for styling

**Comment by GauravGupta993** [comment]
> @GauravGupta993 The code follows only tailwind css rather than using plain css. It just uses more memory compared to tailwind. Delete all css files and use tailwind for styling

I am not very knowledgeable about tailwind CSS, so it might take some time (around 2-3 days) to learn and make changes. Also, after making all changes in tailwind CSS this issue will be for a total of 50 points, right?

**Comment by rohan9024** [comment]
@GauravGupta993 some of the links are not working.... it seems you have implemented some of them only 

And secondly, The UI looks very basic and also has very less content. You take your time to implement this in a better way or else you implement the rest of the pages and it will be only for 5 points.

**Comment by rohan9024** [comment]
> > @GauravGupta993 some of the links are not working.... it seems you have implemented some of them only
> > And secondly, The UI looks very basic and also has very less content. You take your time to implement this in a better way or else you implement the rest of the pages and it will be only for 5 points.
> 
> From the footer, I removed the Legal & Privacy link as it would have had the same content as the Privacy Policy and Terms and Conditions and I was unable to think of what content to add for ENGLISH(INTL) link. Also, for Twitter and Instagram links in Navbar, currently I am redirecting them to their official sites. Can I get some examples of which content I can add there? I believe all other links must be working. For all other links, I will add more content and work on their UI.

Okay, Alright np. For content, you can use chatgpt for that by providing the context.

**Comment by rohan9024** [comment]
Closing this because of no response.

**Pull request closed without merging**
