### PR TITLE
fix: slow scrolling effect on website

### PR DESCRIPTION
**Pull request by SharmaDhruv2511**
I have fixed the slow scrolling in the website  #118 . now the website is smooth scrollable.

### CODE REVIEW

**Comment by rohan9024** [comment]
Naah it's not working. Maybe can you work on the other issues?

**Comment by SharmaDhruv2511** [comment]
the seconds  before the damping makes the scrolling slow.  when i update it , it works fine on my system.

**Comment by SharmaDhruv2511** [comment]
If there are some other changes please markdown

**Comment by rohan9024** [comment]
@SharmaDhruv2511 Looks like it's scrolling bluntly. I have no change except this one.

**Comment by rohan9024** [comment]
@SharmaDhruv2511 Any updates? Are you working on this?

**Comment by rohan9024** [comment]
Closing this because of no response.

**Pull request closed without merging**
