### PR TITLE
New banner with cards are added to all pages

### PR DESCRIPTION
**Pull request by Sami3160**
issue #133 resolved

-Cards like banners are added on every page, like men, women kids, shoes, sales.
-Banner from all pages are responsive.
-For more 'pluggable look' library is used.
-All Images are good high quality
-5-6 different cards are added as banner with effects and slide animation 
-Title and description is meant to be meaningful with images and nav link.
-Every page, every card have unique image, title, description with well relatable meaning...
-On every page changes cards are added, yet code is also kept optimized, with no redundancy.
-Cards can be changed by mouse, or by clicking on a card then using keyboard buttons (to use keyboard focus on card i required)
here is screenshot of banner cards:
Screenshot (114)
-page of shoes section
Screenshot (115)
-responsive testing
Screenshot (116)
Screenshot (117)
-Can change the the cards as slides by both mouse and keyboard 
Screenshot (118)

please do check my pr, it was soo hard as react newbie 😅but it was so fun also😁

### CODE REVIEW

**Comment by rohan9024** [comment]
Great Work! Can you add this styling `absolute z-10 flex flex-col p-10 space-y-2  backdrop-blur-sm backdrop-opacity-70  rounded-2xl` because the background color for the text looks quite odd.

**Comment by Sami3160** [comment]
> 1. Great Work! Can you add this styling `absolute z-10 flex flex-col p-10 space-y-2  backdrop-blur-sm backdrop-opacity-70  rounded-2xl` because the background color for the text looks quite odd.
> 2. Looks like you have not added the cards on the sales page. Do add that.
> 3. Remove the cards which you have added on the homepage(we already have plenty of cards)
> 
> image
> 
> 4. You have repeated the title on all pages. Please add unique titles on all pages.
> 
> image
> 
> 5. In the above image, add filter and sort after the cards since the filters being on top with the cards doesn't make any sense.

Okay, but clicking on sales was redirecting to home page, i didnt find any special Sales page,
Screenshot (119)
see in code their is no link for sales.
And one more doubt, about the title, what exactly unique i should add? like new text, or dialog or description or image or design or something else? 
Rest other changes will be done surely!!!

**Comment by Sami3160** [comment]
> > > 1. Great Work! Can you add this styling `absolute z-10 flex flex-col p-10 space-y-2  backdrop-blur-sm backdrop-opacity-70  rounded-2xl` because the background color for the text looks quite odd.
> > > 2. Looks like you have not added the cards on the sales page. Do add that.
> > > 3. Remove the cards which you have added on the homepage(we already have plenty of cards)
> > > 
> > > image
> > > 
> > > 4. You have repeated the title on all pages. Please add unique titles on all pages.
> > > 
> > > image
> > > 
> > > 5. In the above image, add filter and sort after the cards since the filters being on top with the cards doesn't make any sense.
> > 
> > 
> > Okay, but clicking on sales was redirecting to home page, i didnt find any special Sales page, Screenshot (119) see in code their is no link for sales. And one more doubt, about the title, what exactly unique i should add? like new text, or dialog or description or image or design or something else? Rest other changes will be done surely!!!
> 
> For unique titles or any content, you can use chatgpt for generating the content and for sales page you need to create a new page


The content from all cards of all pages was already taken from ChatGPT except images and design so all text is different from each other of all pages so as content what unique thing i should get?


Okay, so unique means just new text.. right? no new design or anything? okay then ill be doing it, and about the sales page, their is no data for sales, that is also a problem but ill manage it, and what contents should i add in sales page? Like selling tech related stuff? or trending/ best selling/ best offer products from all catagory or something else?

**Comment by Sami3160** [comment]
> > > > 1. Great Work! Can you add this styling `absolute z-10 flex flex-col p-10 space-y-2  backdrop-blur-sm backdrop-opacity-70  rounded-2xl` because the background color for the text looks quite odd.
> > > > 2. Looks like you have not added the cards on the sales page. Do add that.
> > > > 3. Remove the cards which you have added on the homepage(we already have plenty of cards)
> > > > 
> > > > image
> > > > 
> > > > 4. You have repeated the title on all pages. Please add unique titles on all pages.
> > > > 
> > > > image
> > > > 
> > > > 5. In the above image, add filter and sort after the cards since the filters being on top with the cards doesn't make any sense.
> > > 
> > > 
> > > Okay, but clicking on sales was redirecting to home page, i didnt find any special Sales page, Screenshot (119) see in code their is no link for sales. And one more doubt, about the title, what exactly unique i should add? like new text, or dialog or description or image or design or something else? Rest other changes will be done surely!!!
> > 
> > 
> > For unique titles or any content, you can use chatgpt for generating the content and for sales page you need to create a new page
> 
> The content from all cards of all pages was already taken from ChatGPT except images and design so all text is different from each other of all pages so as content what unique thing i should get? Edit: and i initially took 5 unique cards for each page, those 5 cards rotate like a circular queue. So that why you are seeing single card multiple time
> 
> Okay, so unique means just new text.. right? no new design or anything? okay then ill be doing it, and about the sales page, their is no data for sales, that is also a problem but ill manage it, and what contents should i add in sales page? Like selling tech related stuff? or trending/ best selling/ best offer products from all catagory or something else?

@rohan9024 please clear my doubts, i waant to merge this pr before any more merge conflicts happen.

**Comment by rohan9024** [comment]
@Sami3160 Have you used chatgpt before for content generation? Let me show you an example like how you can prompt and get content out of it.  

Follow this link--> https://chat.openai.com/share/9002b2d4-e2d7-4d0d-aac6-2003dcfe36b0

You have the freedom to design the entire sales page by your choice. Refer other ecommerce brands and how they design sales page, how they create components, grid like structures and then implement the design/ content.

**Comment by rohan9024** [comment]
@Sami3160 Have you used chatgpt before for content generation? Let me show you an example like how you can prompt and get content out of it.  

Follow this link--> https://chat.openai.com/share/9002b2d4-e2d7-4d0d-aac6-2003dcfe36b0

You have the freedom to design the entire sales page by your choice. Refer other ecommerce brands and how they design sales page, how they create components, grid like structures and then implement the design/ content.

**Comment by Sami3160** [comment]
> @Sami3160 Have you used chatgpt before for content generation? Let me show you an example like how you can prompt and get content out of it.
> 
> Follow this link--> https://chat.openai.com/share/9002b2d4-e2d7-4d0d-aac6-2003dcfe36b0
> 
> You have the freedom to design the entire sales page by your choice. Refer other ecommerce brands and how they design sales page, how they create components, grid like structures and then implement the design/ content.

Thankyou very much sir for guidance😊!!! and about the unique cards, thrie are 5 unique card on every page which you see again and again in cyclic rotation...it looks repeated as you told me, so instead of 5 unique cards should i add more? like 8?

**Comment by rohan9024** [comment]
@Sami3160 I didn't get it what you said ....... let's first implement the above objectives and then focus on the extra functionalities for bonus. 

Have you pushed the commits?

**Comment by Sami3160** [comment]
> @Sami3160 I didn't get it what you said ....... let's first implement the above objectives and then focus on the extra functionalities for bonus.
> 
> Have you pushed the commits?

not yet, but today ill commit all changes in one shot is possible

**Comment by rohan9024** [comment]
> > @Sami3160 I didn't get it what you said ....... let's first implement the above objectives and then focus on the extra functionalities for bonus.
> > Have you pushed the commits?
> 
> not yet, but today ill commit all changes in one shot is possible

Alright, All the best😄

Happy Coding!

**Pull request merged**
