### PR TITLE
"close button has removed in search bar"

### PR DESCRIPTION
**Pull request by Prasad-mutnale**
hello @rohan9024 please check it once i remove the "close button" in search please go through once if any queries let me know
Thank you for assigning me this issue

### CODE REVIEW

**Comment by rohan9024** [comment]
> hello @rohan9024 please check it once i remove the "close button" in search please go through once if any queries let me know
> Thank you for assigning me this issue

@Prasad-mutnale can you please record a video of what you have implemented?

**Comment by Prasad-mutnale** [comment]
> > hello @rohan9024 please check it once i remove the "close button" in search please go through once if any queries let me know
> > Thank you for assigning me this issue
> 
> @Prasad-mutnale can you please record a video of what you have implemented?

yeah sure but i will show in html and css is it okay ?

**Comment by rohan9024** [comment]
> > > hello @rohan9024 please check it once i remove the "close button" in search please go through once if any queries let me know
> > > Thank you for assigning me this issue
> > 
> > @Prasad-mutnale can you please record a video of what you have implemented?
> 
> yeah sure but i will show in html and css is it okay ?
> 

Start screen recording and show your implementation

**Comment by Prasad-mutnale** [comment]
https://user-images.githubusercontent.com/81313711/208731572-59683ac6-dd1c-418f-8f9b-32d76ffaca9d.mp4

hey @rohan9024 i have shared video in which i used html and css to remove close button

**Comment by rohan9024** [comment]
> 
> https://user-images.githubusercontent.com/81313711/208731572-59683ac6-dd1c-418f-8f9b-32d76ffaca9d.mp4
> 
> hey @rohan9024 i have shared video in which i used html and css to remove close button 

Ohh noo not like that.... Follow the contributions.md file 

Find the component of the search bar I'm talking about and then implement that on the same page itself

**Comment by Prasad-mutnale** [comment]
> > search.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > hey @rohan9024 i have shared video in which i used html and css to remove close button
> 
> Ohh noo not like that.... Follow the contributions.md file
> 
> Find the component of the search bar I'm talking about and then implement that on the same page itself

ok i will go through...

**Pull request closed without merging**
