### PR TITLE
Added 4 types of sort feature.

### LINKED ISSUE #66: Add more ecommerce features on website

### PR DESCRIPTION
**Pull request by Dibyendu303**
Closes #66 . Added 4 types of sort feature.

### 4. Sort by name - Z to A

Added video preview:

https://user-images.githubusercontent.com/66685553/208252886-369a1c7e-e072-41d1-b293-f52ea8eb7f21.mp4

### CODE REVIEW

**Comment by Dibyendu303** [comment]
@rohan9024 Product images will be visible after deployment because the images are hosted on the server.

**Comment by rohan9024** [comment]
@Dibyendu303 alright fine.... can you please add sort filter dropdown like this -->


image

https://www.nike.com/in/w/mens-shoes-nik1zy7ok

**Review by rohan9024 — APPROVED** [review]

**Comment by rohan9024** [comment]
@Dibyendu303 also this filter dropdown is appearing on every page .... please fix it-->

image

image

**Comment by Dibyendu303** [comment]
@rohan9024 Updated now
Screenshot (2127)

**Comment by rohan9024** [comment]
@Dibyendu303 can you design  the same way its on nike's website

image

**Comment by Dibyendu303** [comment]
@rohan9024 is it okay now ? 
Screenshot (2162)

**Pull request closed without merging**
