### PR TITLE
Revert "Admin"

### PR DESCRIPTION
**Pull request by rohan9024**
Reverts rohan9024/ecommerce#69

### CODE REVIEW

**Comment by rohan9024** [comment]
@kshitij01042002 After I click on other routes like men, women, shoes, I get a page like this-->

image

This is same for all pages. Please fix

**Comment by kshitij01042002** [comment]
The reason for that is you don't have any items in your database. Add some items add you'll be good to go

**Comment by kshitij01042002** [comment]
Merge the changes. Add some products from admin page

**Comment by rohan9024** [comment]
@kshitij01042002 keep the data which was before and on top of it we should be able to add more products

**Comment by kshitij01042002** [comment]
@rohan9024 Done!

**Pull request closed without merging**
