### PR TITLE
Database

### PR DESCRIPTION
**Pull request by kshitij01042002**
#57 
I have created kind of like a database schema to store data
All the data is rendered from firebase database
I have manually filled all the data into the database.
Soo the data which is rendering is from my database

You can see the demo here [demo](https://ecommerce-gnkrg1q2o-kshitij01042002.vercel.app)

This is the like a pre-requiste step for issue #58

### CODE REVIEW

**Comment by rohan9024** [comment]
@kshitij01042002 please fix the errors

**Comment by kshitij01042002** [comment]
@rohan9024 the PR doesn't contain any errors. See demo on https://ecommerce-gnkrg1q2o-kshitij01042002.vercel.app/ it's showing errors in your deployment cause you haven't declared env variables in your versile environment.

**Comment by rohan9024** [comment]
@kshitij01042002 stop working on the database

**Comment by rohan9024** [comment]
@kshitij01042002 have you made the admin page?

**Comment by kshitij01042002** [comment]
> @kshitij01042002 have you made the admin page?

Working on it, will raise try to raise the PR by midnight today

**Comment by rohan9024** [comment]
@kshitij01042002 alright if you say so........I have rolled back the website now its live now

**Comment by rohan9024** [comment]
@kshitij01042002 we're still having some issues while deploying 

image

**Comment by kshitij01042002** [comment]
Did you set the environment variables in your vercile deployment?

**Comment by kshitij01042002** [comment]
I'll suggest don't merge database PR yet wait till admin page is done too and merge all the changes together.
If you want to see the demo visit my vercile deployment
https://ecommerce-gnkrg1q2o-kshitij01042002.vercel.app/

**Comment by rohan9024** [comment]
@kshitij01042002 no, I haven't merged your PR. You can go on with the admin page....lemme know once you're done

**Pull request merged**
